version: 0.2

phases:
  build:
    commands:
      - mkdir dist
      - cp *.html dist/

  post_build:
    commands:
      - aws s3 sync ./dist s3://<INSERT-YOUR-BUCKET-NAME-HERE>/ --delete --acl=public-read
