Parameters:
  DomainName:
    Description: The site domain name.
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<![.-])
    ConstraintDescription: Must be a valid domain name.
    Default: abelperezmartinez.com #abelperez.info
  SubDomainName:
    Description: The site subdomain name i.e www
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-]{1,15}(?<![.-])
    ConstraintDescription: Must be a valid subdomain name.
    Default: www #test
  IncludeRedirectToSubDomain:
    Description: Whether it should include a redirection from the naked domain to the subdomain.
    Type: String
    Default: false
    AllowedValues: [true, false]
  SSLCertificate:
    Description: The ARN of the SSL certificate
    Type: String
    Default: arn:aws:acm:us-east-1:976153948458:certificate/e57928e3-8268-468c-8001-5bf011eec0a2 #arn:aws:acm:us-east-1:976153948458:certificate/ac70d662-f70a-4cce-be8b-81fe1946f348
  HostedZone:
    Description: Z2FDTNDATAQYW2 for CloudFront
    Type: String
    Default: Z2FDTNDATAQYW2

Conditions:
  includeRedirect: !Equals [!Ref IncludeRedirectToSubDomain, "true"]

Resources:
  # S3 buckets 
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  RedirectBucket:
    Type: AWS::S3::Bucket
    Condition: includeRedirect # conditionally created
    Properties:
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Sub www.${DomainName}
          Protocol: https
  # CloudFront distributions
  WWWCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub ${SubDomainName}.${DomainName}
        DefaultRootObject: index.html
        CacheBehaviors: []
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          TargetOriginId: S3Bucket
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
            Headers: []
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 31536000
          SmoothStreaming: false
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt StaticSiteBucket.WebsiteURL]]
            Id: S3Bucket
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        PriceClass: PriceClass_100
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: !Ref SSLCertificate
          MinimumProtocolVersion: TLSv1.1_2016
  RedirectCloudFront:
    Type: AWS::CloudFront::Distribution
    Condition: includeRedirect # conditionally created
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub ${DomainName}
        CacheBehaviors: []
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          TargetOriginId: S3Bucket
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
            Headers: []
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 31536000
          SmoothStreaming: false
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt RedirectBucket.WebsiteURL]]
            Id: S3Bucket
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        PriceClass: PriceClass_100
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: !Ref SSLCertificate
          MinimumProtocolVersion: TLSv1.1_2016
  # Route53 A record
  WWWRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        HostedZoneId: !Ref HostedZone
        DNSName: !GetAtt WWWCloudFront.DomainName
      HostedZoneName: !Sub ${DomainName}.
      Name: !Sub ${SubDomainName}.${DomainName}.
      Type: A
  MainRecordSet:
    Type: AWS::Route53::RecordSet
    Condition: includeRedirect # conditionally created
    Properties:
      AliasTarget:
        HostedZoneId: !Ref HostedZone
        DNSName: !GetAtt RedirectCloudFront.DomainName
      HostedZoneName: !Sub ${DomainName}.
      Name: !Sub ${DomainName}.
      Type: A
  # CodeCommit repository
  CodeCommitRepository:
     Type: AWS::CodeCommit::Repository
     Properties:
      RepositoryDescription: Repository to store de source code
      RepositoryName: !Sub ${SubDomainName}.${DomainName}-web
  # CodeCommit user & policy
  CodeCommitUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub CodeCommitUserPolicy for Repo ${CodeCommitRepository.Name}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Sid: AllowGitCommandlineOperations
          Effect: Allow
          Action:
            - codecommit:GitPull
            - codecommit:GitPush
          Resource: !GetAtt CodeCommitRepository.Arn
  CodeCommitUser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - !Ref CodeCommitUserPolicy
  # CodeBuild project, Role and Policy
  CodeBuildUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub CodeBuildUserPolicy for CodeBuild project ${AWS::StackName}-builder
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AccessLogGroupsS3ListObjects
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - s3:ListObjects
            Resource: "*"
          - Sid: AccessGitLogs
            Effect: Allow
            Action:
              - codecommit:GitPull
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}-builder
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}-builder:*
              - !GetAtt CodeCommitRepository.Arn
          - Sid: AccessS3staticBucket
            Effect: Allow
            Action: s3:*
            Resource:
              - !GetAtt StaticSiteBucket.Arn
              - !Sub ${StaticSiteBucket.Arn}/*
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Path: /service-role/
      ManagedPolicyArns:
        - !Ref CodeBuildUserPolicy
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-builder
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:7.0.0
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODECOMMIT
        Location: !GetAtt CodeCommitRepository.CloneUrlHttp
      TimeoutInMinutes: 5
  # CloudWatch event rule, Role and Policy
  CloudWatchEventRulePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub CloudWatchEventRulePolicy for CloudWatch event rule ${AWS::StackName}-start-build-rule
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - codebuild:StartBuild
            Resource:
              - !GetAtt CodeBuildProject.Arn
  CloudWatchEventRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Path: /service-role/
      ManagedPolicyArns:
        - !Ref CloudWatchEventRulePolicy
  AutomaticBuildRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Connects changes in CodeCommit to start CodeBuild project buid
      RoleArn: !GetAtt CloudWatchEventRuleRole.Arn
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources:
          - !GetAtt CodeCommitRepository.Arn
      State: ENABLED
      Targets:
        - Arn: !GetAtt CodeBuildProject.Arn
          Id: !Sub ${AWS::StackName}-start-build-rule
          RoleArn: !GetAtt CloudWatchEventRuleRole.Arn

Outputs:
  CodeCommitRepositoryCloneUrlHttp:
    Description: Url to clone the CodeCommit repository via HTTPS
    Value: !GetAtt CodeCommitRepository.CloneUrlHttp
  CodeCommitRepositoryCloneUrlSsh:
    Description: Url to clone the CodeCommit repository via SSH
    Value: !GetAtt CodeCommitRepository.CloneUrlSsh