Parameters:
	SSLCertificate: 
		Description: The ARN of the SSL certificate
		Type: String
		Default: arn:aws:acm:us-east-1:976153948458:certificate/ac70d662-f70a-4cce-be8b-81fe1946f348
	HostedZone:
		Description: Z2FDTNDATAQYW2 for CloudFront
		Type: String
		Default: Z2FDTNDATAQYW2
	


Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html



















  # WWWRecordSet:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     AliasTarget:
  #       HostedZoneId:
  #         Ref: 










    #     "WWWRecordSet": {
		# 	"Type": "AWS::Route53::RecordSet",
		# 	"Properties": {
		# 		"AliasTarget": {
		# 			"HostedZoneId": {
		# 				"Ref": "HostedZone"
		# 			},
		# 			"DNSName": {
		# 				"Fn::Sub": "${WWWCloudFront.DomainName}"
		# 			}
		# 		},
		# 		"HostedZoneName": {
		# 			"Fn::Sub": "${DomainName}."
		# 		},
		# 		"Name": {
		# 			"Fn::Sub": "www.${DomainName}."
		# 		},
		# 		"Type": "A"
		# 	}
		# },