Parameters:
  DomainName:
    Description: The site domain name (non www).
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<![.-])
    ConstraintDescription: Must be a valid domain name.
    Default: abelperez.info
  SubDomainName:
    Description: The site domain name (non www).
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-]{1,15}(?<![.-])
    ConstraintDescription: Must be a valid subdomain name.
    Default: test
  SSLCertificate:
    Description: The ARN of the SSL certificate
    Type: String
    Default: arn:aws:acm:us-east-1:976153948458:certificate/ac70d662-f70a-4cce-be8b-81fe1946f348
  HostedZone:
    Description: Z2FDTNDATAQYW2 for CloudFront
    Type: String
    Default: Z2FDTNDATAQYW2

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WWWCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub ${SubDomainName}.${DomainName} # test.abelperez.info
        DefaultRootObject: index.html
        CacheBehaviors: []
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          TargetOriginId: S3Bucket
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
            Headers: []
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 31536000
          SmoothStreaming: false
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt StaticSiteBucket.DomainName
            Id: S3Bucket
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        PriceClass: PriceClass_100
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: !Ref SSLCertificate
          MinimumProtocolVersion: TLSv1.1_2016
  WWWRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        HostedZoneId: !Ref HostedZone
        DNSName: !GetAtt WWWCloudFront.DomainName
      HostedZoneName: !Sub ${DomainName}. # abelperez.info.
      Name: !Sub ${SubDomainName}.${DomainName}. # test.abelperez.info.
      Type: A







#     "WWWRecordSet": {
# 	"Type": "AWS::Route53::RecordSet",
# 	"Properties": {
# 		"AliasTarget": {
# 			"HostedZoneId": {
# 				"Ref": "HostedZone"
# 			},
# 			"DNSName": {
# 				"Fn::Sub": "${WWWCloudFront.DomainName}"
# 			}
# 		},
# 		"HostedZoneName": {
# 			"Fn::Sub": "${DomainName}."
# 		},
# 		"Name": {
# 			"Fn::Sub": "www.${DomainName}."
# 		},
# 		"Type": "A"
# 	}
# },


















  # WWWRecordSet:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     AliasTarget:
  #       HostedZoneId:
  #         Ref: 

